name: Build and Deploy
on: # 监听 main 分支上的 push 事件
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 构建环境使用 ubuntu
    steps:
      - name: Checkout  # 将代码拉到虚拟机
        uses: actions/checkout@v1.0.0
        with:
          node-version: 18.x
          cache: yarn
      - name: Install
        run: yarn && yarn run publish
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
