name: Publish Electron
on: # 监听 main 分支上的 push 事件
  push:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  CSC_LINK: ./cert/mockplus.p12
  CSC_KEY_PASSWORD: "123456"
jobs:
  # build_on_mac:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3.0.0
      
  #     - name: Install Node
  #       uses: actions/setup-node@v3.0.0

  #     - name: Install dependencies
  #       run: npm install 

  #     - name: Publish Electron App
  #       run: npm run publish
  build_on_mac_11:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      
      - name: Install Node
        uses: actions/setup-node@v3.0.0

      - name: Install dependencies
        run: npm install 

      - name: Publish Electron App
        run: npm run publish
  build_on_window:
    runs-on: windows-latest
    steps:
      - name: Checkout
        # uses: ver
        uses: actions/checkout@v3.0.0
      
      - name: Install Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Publish Electron App
        run: npm run publish

  # build_on_win-2019:
  #   runs-on: windows-2019
  #   steps:
  #     - name: Checkout
  #       uses: ver
  #       uses: actions/checkout@v3.0.0
      
  #     - name: Install Node
  #       uses: actions/setup-node@v3.0.0

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Publish Electron App
  #       run: npm run publish

  # build_on_ubuntu:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3.0.0
      
  #     - name: Install Node
  #       uses: actions/setup-node@v3.0.0

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Publish Electron App
  #       run: npm run publish

        
